vim.keymap.set('n', '<leader>f', ":Telescope<CR>", {})
vim.keymap.set('n', '<leader>ff', ":Telescope find_files<CR>", {})
vim.keymap.set('n', '<leader>fg', ":Telescope live_grep<CR>", {})
vim.keymap.set('n', '<leader>fr', ":Telescope grep_string<CR>", {})
vim.keymap.set('n', '<leader>ft', ":Telescope buffers<CR>", {})
vim.keymap.set('n', '<leader>fh', ":Telescope help_tags<CR>", {})
vim.keymap.set('n', '<leader>fc', ":Telescope commands<CR>", {})
vim.keymap.set('n', '<leader>fb', ":Telescope bookmark<CR>", {})
