local navic = require 'nvim-navic'
navic.setup {
  {
    Array = '',
    Boolean = '',
    Class = '',
    Color = '',
    Constant = '',
    Constructor = '',
    Enum = '',
    EnumMember = '',
    Event = '',
    Field = '',
    File = '',
    Folder = '',
    Function = '',
    Interface = '',
    Key = '',
    Keyword = '',
    Method = '',
    Module = '',
    Namespace = '',
    Null = 'ﳠ',
    Number = '',
    Object = '',
    Operator = '',
    Package = '',
    Property = '',
    Reference = '',
    Snippet = '',
    String = '',
    Struct = '',
    Text = '',
    TypeParameter = '',
    Unit = '',
    Value = '',
    Variable = '',
  },
  lsp = {
    auto_attach = true,
    -- preference = {'html','tsserver'}
  },
  highlight = true,
  click = true,
  lazy_update_context = true,
  safe_output = true,
}